<template>
  <v-card>
    <v-card-title>
      this shows best way to use asyncData
    </v-card-title>
    <v-card-text>
      <span class="mr-3">
        the following badge is generated by asyncData =>
      </span>
      <v-badge color="primary">
        <span slot="badge">{{ foo }}</span>
      </v-badge>
      <br />
    </v-card-text>
      <prism-editor :code="code" language="js" line-numbers readonly></prism-editor>
  </v-card>
</template>

<script lang="ts">
  import { Component, Vue } from "nuxt-property-decorator"
  interface Test {
    foo: string
    bar: number
  }
  
  @Component({
    asyncData (): Test {
        return {
          foo: 'hi, this is a text generated via asyncData',
          bar: 1
        }
      }
  })
  
  export default class App extends Vue {
    code: string = `
      // and this is how we do it in the @Component decorator

      interface Test {
        foo: string
        bar: number
      }

      @Component({
        asyncData (): Test {
            return {
              foo: 'hi, this is a text generated via asyncData',
              bar: 1
            }
          }
      })
    `
  };
</script>

